name: Test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  chmod +x ./install_hclw.sh
                  ./install_hclw.sh
                  python3 -m pip install -r requirements.txt
            - name: Analysing the code with pylint
              run: |
                  python3 test/test.py
